name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tox-utils:
    name: tox-utils
    runs-on: ubuntu-latest
    container:
      image: themattrix/tox
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Run tox
        working-directory: utils
        run: tox

  tox-testing:
    name: tox-testing
    runs-on: ubuntu-latest
    container:
      image: themattrix/tox
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Run tox
        working-directory: testing
        run: tox
